### ISSUE TITLE
What does DELAY mean?

### ISSUE THREAD

**Issue by buhtz** [apollo-ng/xfce-planet#7]
```
# Satellite file switch delay (number of renders between switches)
DELAY=120
```

I don't really understand what this means. Can you explain please.

**Comment by chron0** [comment]
The default is DELAY=5, which means, xplanet will be executed 5 times before switching to the next available TLE set, so we can automagically cycle through all different sets (Iridium, NOSS or whatever else TLE you would like to put into the download-tle.sh file).

**Comment by buhtz** [comment]
So the next TLE-set is selected each (DELAY * SLEEP_ON_AC) seconds?

**Comment by chron0** [comment]
Exactly.
